// lib/ai/daily_briefing_service.dart
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import 'package:mindcore_ai/services/mood_log_service.dart';
import 'package:mindcore_ai/pages/helpers/journal_service.dart';
import 'package:mindcore_ai/env/env.dart';

/// The time-of-day slot the user is in.
enum TimeSlot { earlyMorning, morning, afternoon, evening, night }

/// A rich, personalised daily briefing generated by the AI.
/// Cached per [date + time-slot] so we never spam the API.
class DailyBriefingService {
  static const _cacheKey = 'daily_briefing_v1';
  static const _cacheSlotKey = 'daily_briefing_slot_v1';

  // In-memory cache — survives hot-reloads, cleared on cold restart
  static String? _memCache;
  static String? _memCacheSlot;

  // ── Public API ─────────────────────────────────────────────────────────

  /// Returns a personalised 1–2 sentence briefing for the current moment.
  /// Hits AI once per [date + time-slot], then returns cached result.
  static Future<String> getBriefing() async {
    final slot = _currentSlot();
    final slotKey = _slotKey(slot);

    // 1. In-memory cache hit
    if (_memCache != null && _memCacheSlot == slotKey) {
      return _memCache!;
    }

    // 2. SharedPreferences cache hit
    final prefs = await SharedPreferences.getInstance();
    final cachedSlot = prefs.getString(_cacheSlotKey);
    final cachedText = prefs.getString(_cacheKey);
    if (cachedSlot == slotKey &&
        cachedText != null &&
        cachedText.isNotEmpty) {
      _memCache = cachedText;
      _memCacheSlot = slotKey;
      return cachedText;
    }

    // 3. Generate fresh from AI
    final briefing = await _generate(slot);
    _memCache = briefing;
    _memCacheSlot = slotKey;
    await prefs.setString(_cacheKey, briefing);
    await prefs.setString(_cacheSlotKey, slotKey);
    return briefing;
  }

  /// Force-refresh, ignoring any cache (call when user logs a new mood).
  static Future<String> refresh() async {
    _memCache = null;
    _memCacheSlot = null;
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_cacheKey);
    await prefs.remove(_cacheSlotKey);
    return getBriefing();
  }

  // ── Internal ───────────────────────────────────────────────────────────

  static TimeSlot _currentSlot() {
    final h = DateTime.now().hour;
    if (h >= 5 && h < 9) return TimeSlot.earlyMorning;
    if (h >= 9 && h < 13) return TimeSlot.morning;
    if (h >= 13 && h < 18) return TimeSlot.afternoon;
    if (h >= 18 && h < 22) return TimeSlot.evening;
    return TimeSlot.night;
  }

  static String _slotKey(TimeSlot slot) {
    final now = DateTime.now();
    final date =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
    return '${date}_${slot.name}';
  }

  static Future<String> _generate(TimeSlot slot) async {
    try {
      final context = await _buildContext(slot);
      final message = await _callAI(context);
      return message.isNotEmpty ? message : _fallback(slot);
    } catch (_) {
      return _fallback(slot);
    }
  }

  static Future<Map<String, dynamic>> _buildContext(TimeSlot slot) async {
    final now = DateTime.now();

    // Mood trend
    final last7 = await MoodRepo.instance.last7Normalized();
    final avgMood = last7.isEmpty
        ? null
        : last7.reduce((a, b) => a + b) / last7.length;
    final moodTrend = _moodTrendLabel(last7);

    // Today's mood (if already logged)
    final todayMeta = await MoodLogService.todayMeta();
    final todayMoodLabel = todayMeta['label'] ?? '';
    final todayMoodEmoji = todayMeta['emoji'] ?? '';

    // Latest journal note — safe substring, no characters package needed
    String journalSnippet = '';
    try {
      final entries = await JournalService.getEntries();
      if (entries.isNotEmpty) {
        final note = entries.first.note.trim();
        journalSnippet =
            note.length > 200 ? note.substring(0, 200) : note;
      }
    } catch (_) {}

    // Day of week (for pattern hints)
    const days = [
      'Monday', 'Tuesday', 'Wednesday',
      'Thursday', 'Friday', 'Saturday', 'Sunday'
    ];
    final dayName = days[now.weekday - 1];

    return {
      'slot': slot.name,
      'hour': now.hour,
      'dayName': dayName,
      'avgMood': avgMood,
      'moodTrend': moodTrend,
      'todayMoodLabel': todayMoodLabel,
      'todayMoodEmoji': todayMoodEmoji,
      'journalSnippet': journalSnippet,
    };
  }

  static String _moodTrendLabel(List<double> last7) {
    if (last7.isEmpty) return 'unknown';
    final nonZero = last7.where((v) => v > 0).toList();
    if (nonZero.isEmpty) return 'unknown';
    final avg = nonZero.reduce((a, b) => a + b) / nonZero.length;
    if (avg >= 0.70) return 'good';
    if (avg >= 0.50) return 'moderate';
    if (avg >= 0.30) return 'low';
    return 'struggling';
  }

  static Future<String> _callAI(Map<String, dynamic> ctx) async {
    final apiKey = Env.openaiKey;
    if (apiKey.trim().isEmpty) return '';

    final slot = ctx['slot'] as String;
    final hour = ctx['hour'] as int;
    final dayName = ctx['dayName'] as String;
    final moodTrend = ctx['moodTrend'] as String;
    final todayMoodLabel = ctx['todayMoodLabel'] as String;
    final todayMoodEmoji = ctx['todayMoodEmoji'] as String;
    final journalSnippet = ctx['journalSnippet'] as String;

    // Time-of-day label — standard if/else, no Dart 3 switch expression
    String timeLabel;
    if (slot == 'earlyMorning') {
      timeLabel = 'early morning ($hour:00)';
    } else if (slot == 'morning') {
      timeLabel = 'morning ($hour:00)';
    } else if (slot == 'afternoon') {
      timeLabel = 'afternoon ($hour:00)';
    } else if (slot == 'evening') {
      timeLabel = 'evening ($hour:00)';
    } else {
      timeLabel = 'night ($hour:00)';
    }

    // Build the prompt
    final sb = StringBuffer();
    sb.writeln(
        'You are MindCore AI, a warm and emotionally intelligent mental wellness companion.');
    sb.writeln(
        'Write a single short, personal briefing message (1–2 sentences, max 30 words) '
        'for the user right now. The message must acknowledge the actual time of day correctly.');
    sb.writeln();
    sb.writeln('CONTEXT:');
    sb.writeln('- Current time: $timeLabel on $dayName');
    sb.writeln('- Mood trend (last 7 days): $moodTrend');
    if (todayMoodLabel.isNotEmpty) {
      sb.writeln(
          "- User already logged today's mood: $todayMoodEmoji $todayMoodLabel");
    } else {
      sb.writeln("- User has not logged today's mood yet");
    }
    if (journalSnippet.isNotEmpty) {
      sb.writeln('- Latest journal note (context only): "$journalSnippet"');
    }
    sb.writeln();
    sb.writeln('RULES:');
    sb.writeln(
        "- Never say 'good morning' if it is afternoon, evening, or night");
    sb.writeln(
        "- Never say 'good evening' if it is morning or afternoon");
    sb.writeln(
        '- Be warm, not clinical. No emojis. No asterisks. No quotes.');
    sb.writeln(
        '- Match the energy of the time: gentle/calm at night, energising in the morning, grounding in the afternoon');
    sb.writeln(
        '- If mood trend is low or struggling, be compassionate not cheerful');
    sb.writeln('- Output ONLY the message. Nothing else.');

    final response = await http
        .post(
          Uri.parse('https://api.openai.com/v1/chat/completions'),
          headers: {
            'Authorization': 'Bearer $apiKey',
            'Content-Type': 'application/json',
          },
          body: jsonEncode({
            'model': 'gpt-4o-mini',
            'messages': [
              {'role': 'user', 'content': sb.toString()}
            ],
            'temperature': 0.75,
            'max_tokens': 60,
          }),
        )
        .timeout(const Duration(seconds: 12));

    if (response.statusCode != 200) return '';

    final json = jsonDecode(response.body) as Map<String, dynamic>;
    final choices = json['choices'] as List?;
    if (choices == null || choices.isEmpty) return '';
    final content = (choices.first as Map<String, dynamic>)['message']
            ?['content']
            ?.toString()
            .trim() ??
        '';
    return content;
  }

  /// Fallback if AI is unavailable — still time-aware.
  static String _fallback(TimeSlot slot) {
    switch (slot) {
      case TimeSlot.earlyMorning:
        return 'Early start. Take a breath before the day begins.';
      case TimeSlot.morning:
        return 'Morning. A good moment to set one steady intention.';
      case TimeSlot.afternoon:
        return 'Afternoon check-in. How is the day treating you so far?';
      case TimeSlot.evening:
        return 'Evening. Time to let the day settle.';
      case TimeSlot.night:
        return 'Late night. Be gentle with yourself right now.';
    }
  }
}
